name: learning_piano
description: "Learning Piano Flutter App"
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ^3.6.2

dependencies:
  auto_route: ^9.3.0+1
  flutter:
    sdk: flutter
  flutter_midi_pro: ^3.1.4
  talker_flutter: ^4.6.12
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  riverpod_annotation: ^2.6.1
  universal_platform: ^1.1.0
  window_manager: ^0.4.3

dev_dependencies:
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/soundfont/
